import type { Metadata } from 'next';
import { Manrope } from 'next/font/google';
import './globals.css';
import Config from '@/constants/config';
import { ThemeProvider } from '@/components/molecules/providers/theme.provider';
import Storage from '@/constants/storage';
import SettingsProvider from '@/components/molecules/providers/settings.provider';
import { TooltipProvider } from '@/components/atoms/tooltip';

const manrope = Manrope({
  variable: '--font-manrope',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Diaz | Stunning Portfolio OS Themed Web',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang={Config.DEFAULT_LOCALE}
      className={`${manrope.variable} h-full overflow-hidden antialiased`}
      suppressHydrationWarning
    >
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme={Config.DEFAULT_THEME}
          storageKey={Storage.THEME}
          disableTransitionOnChange
        >
          <SettingsProvider>
            <TooltipProvider>{children}</TooltipProvider>
          </SettingsProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
